[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
    [plugins.inputs]
      output_path = "reports/lighthouse.html"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/es-es/*"
  to = "/es-es/:splat"
  status = 200

[[redirects]]
  from = "/pt-br/*"
  to = "/pt-br/:splat"
  status = 200











