face_parameters:
  upperFaceStrength: 1.1
  upperFaceSmoothing: 0.001
  lowerFaceStrength: 1.3
  lowerFaceSmoothing: 0.005
  faceMaskLevel: 0.6
  faceMaskSoftness: 0.0085
  skinStrength: 1.0
  eyelidOpenOffset: 0.0
  lipOpenOffset: 0.0
blendshape_parameters:
  enable_clamping_bs_weight: false
  multipliers:
    EyeBlinkLeft: 1.0
    EyeLookDownLeft: 0.0
    EyeLookInLeft: 0.0
    EyeLookOutLeft: 0.0
    EyeLookUpLeft: 0.0
    EyeSquintLeft: 1.2
    EyeWideLeft: 1.1
    EyeBlinkRight: 1.0
    EyeLookDownRight: 0.0
    EyeLookInRight: 0.0
    EyeLookOutRight: 0.0
    EyeLookUpRight: 0.0
    EyeSquintRight: 1.2
    EyeWideRight: 1.1
    JawForward: 0.8
    JawLeft: 0.3
    JawRight: 0.3
    JawOpen: 1.1
    MouthClose: 1.0
    MouthFunnel: 1.3
    MouthPucker: 1.3
    MouthLeft: 0.3
    MouthRight: 0.3
    MouthSmileLeft: 0.9
    MouthSmileRight: 0.9
    MouthFrownLeft: 0.5
    MouthFrownRight: 0.5
    MouthDimpleLeft: 0.8
    MouthDimpleRight: 0.8
    MouthStretchLeft: 0.2
    MouthStretchRight: 0.2
    MouthRollLower: 1.0
    MouthRollUpper: 0.6
    MouthShrugLower: 1.0
    MouthShrugUpper: 0.5
    MouthPressLeft: 0.9
    MouthPressRight: 0.9
    MouthLowerDownLeft: 0.9
    MouthLowerDownRight: 0.9
    MouthUpperUpLeft: 0.9
    MouthUpperUpRight: 0.9
    BrowDownLeft: 1.1
    BrowDownRight: 1.1
    BrowInnerUp: 1.1
    BrowOuterUpLeft: 1.1
    BrowOuterUpRight: 1.1
    CheekPuff: 0.3
    CheekSquintLeft: 1.1
    CheekSquintRight: 1.1
    NoseSneerLeft: 0.9
    NoseSneerRight: 0.9
    TongueOut: 0.0
  offsets:
    EyeBlinkLeft: 0.0
    EyeLookDownLeft: 0.0
    EyeLookInLeft: 0.0
    EyeLookOutLeft: 0.0
    EyeLookUpLeft: 0.0
    EyeSquintLeft: 0.0
    EyeWideLeft: 0.0
    EyeBlinkRight: 0.0
    EyeLookDownRight: 0.0
    EyeLookInRight: 0.0
    EyeLookOutRight: 0.0
    EyeLookUpRight: 0.0
    EyeSquintRight: 0.0
    EyeWideRight: 0.0
    JawForward: 0.0
    JawLeft: 0.0
    JawRight: 0.0
    JawOpen: 0.0
    MouthClose: 0.0
    MouthFunnel: 0.0
    MouthPucker: 0.0
    MouthLeft: 0.0
    MouthRight: 0.0
    MouthSmileLeft: 0.0
    MouthSmileRight: 0.0
    MouthFrownLeft: 0.0
    MouthFrownRight: 0.0
    MouthDimpleLeft: 0.0
    MouthDimpleRight: 0.0
    MouthStretchLeft: 0.0
    MouthStretchRight: 0.0
    MouthRollLower: 0.0
    MouthRollUpper: 0.0
    MouthShrugLower: 0.0
    MouthShrugUpper: 0.0
    MouthPressLeft: 0.0
    MouthPressRight: 0.0
    MouthLowerDownLeft: 0.0
    MouthLowerDownRight: 0.0
    MouthUpperUpLeft: 0.0
    MouthUpperUpRight: 0.0
    BrowDownLeft: 0.0
    BrowDownRight: 0.0
    BrowInnerUp: 0.0
    BrowOuterUpLeft: 0.0
    BrowOuterUpRight: 0.0
    CheekPuff: 0.0
    CheekSquintLeft: 0.0
    CheekSquintRight: 0.0
    NoseSneerLeft: 0.0
    NoseSneerRight: 0.0
    TongueOut: 0.0
live_transition_time: 0.0001
beginning_emotion:
  amazement: 0.0
  anger: 0.0
  disgust: 0.0
  fear: 0.0
  outofbreath: 0.0
  pain: 0.0
  sadness: 0.0
  joy: 0.0
post_processing_parameters:
  emotion_contrast: 1.0
  live_blend_coef: 0.7
  enable_preferred_emotion: false
  preferred_emotion_strength: 0.5
  emotion_strength: 0.7
  max_emotions: 3
emotion_with_timecode_list:
  emotion_with_timecode1:
    time_code: 0.0
    emotions:
      amazement: 0.0
      anger: 0.0
      cheekiness: 0.0
      disgust: 0.0
      fear: 0.0
      grief: 0.0
      joy: 0.0
      outofbreath: 0.0
      pain: 0.0
      sadness: 0.0
